// Generated by Haxe 4.1.3
package haxe;

import haxe.root.*;

@SuppressWarnings(value={"rawtypes", "unchecked"})
public class Resource extends haxe.lang.HxObject
{
	static
	{
		//line 26 "/usr/local/lib/haxe/std/java/_std/haxe/Resource.hx"
		haxe.Resource.content = new haxe.root.Array<java.lang.String>(new java.lang.String[]{});
	}
	
	public Resource(haxe.lang.EmptyObject empty)
	{
	}
	
	
	public Resource()
	{
		//line 25 "/usr/local/lib/haxe/std/java/_std/haxe/Resource.hx"
		haxe.Resource.__hx_ctor_haxe_Resource(this);
	}
	
	
	protected static void __hx_ctor_haxe_Resource(haxe.Resource __hx_this)
	{
	}
	
	
	public static haxe.root.Array<java.lang.String> content;
	
}


