// Generated by Haxe 4.1.3
package haxe;

import haxe.root.*;

@SuppressWarnings(value={"rawtypes", "unchecked"})
public class Timer___hx_ctor_haxe_Timer_128__Fun extends haxe.lang.Function
{
	public Timer___hx_ctor_haxe_Timer_128__Fun()
	{
		//line 128 "/usr/local/lib/haxe/std/haxe/Timer.hx"
		super(0, 0);
	}
	
	
	public static haxe.Timer___hx_ctor_haxe_Timer_128__Fun __hx_current;
	
	@Override public java.lang.Object __hx_invoke0_o()
	{
		//line 128 "/usr/local/lib/haxe/std/haxe/Timer.hx"
		return null;
	}
	
	
}


