// Generated by Haxe 4.1.3
package ln;

import haxe.root.*;

@SuppressWarnings(value={"rawtypes", "unchecked"})
public class FilterResult extends haxe.lang.HxObject
{
	public FilterResult(haxe.lang.EmptyObject empty)
	{
	}
	
	
	public FilterResult(ln.Vector x, boolean y)
	{
		//line 9 "/Users/lingdonghuang/proj/LN.pde/ln/Filter.hx"
		ln.FilterResult.__hx_ctor_ln_FilterResult(this, x, y);
	}
	
	
	protected static void __hx_ctor_ln_FilterResult(ln.FilterResult __hx_this, ln.Vector x, boolean y)
	{
		//line 10 "/Users/lingdonghuang/proj/LN.pde/ln/Filter.hx"
		__hx_this.x = x;
		//line 11 "/Users/lingdonghuang/proj/LN.pde/ln/Filter.hx"
		__hx_this.y = y;
	}
	
	
	public ln.Vector x;
	
	public boolean y;
	
	@Override public java.lang.Object __hx_setField(java.lang.String field, java.lang.Object value, boolean handleProperties)
	{
		//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/Filter.hx"
		{
			//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/Filter.hx"
			boolean __temp_executeDef1 = true;
			//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/Filter.hx"
			if (( field != null )) 
			{
				//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/Filter.hx"
				switch (field.hashCode())
				{
					case 121:
					{
						//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/Filter.hx"
						if (field.equals("y")) 
						{
							//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/Filter.hx"
							__temp_executeDef1 = false;
							//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/Filter.hx"
							this.y = haxe.lang.Runtime.toBool(((java.lang.Boolean) (value) ));
							//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/Filter.hx"
							return value;
						}
						
						//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/Filter.hx"
						break;
					}
					
					
					case 120:
					{
						//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/Filter.hx"
						if (field.equals("x")) 
						{
							//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/Filter.hx"
							__temp_executeDef1 = false;
							//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/Filter.hx"
							this.x = ((ln.Vector) (value) );
							//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/Filter.hx"
							return value;
						}
						
						//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/Filter.hx"
						break;
					}
					
					
				}
				
			}
			
			//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/Filter.hx"
			if (__temp_executeDef1) 
			{
				//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/Filter.hx"
				return super.__hx_setField(field, value, handleProperties);
			}
			else
			{
				//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/Filter.hx"
				throw null;
			}
			
		}
		
	}
	
	
	@Override public java.lang.Object __hx_getField(java.lang.String field, boolean throwErrors, boolean isCheck, boolean handleProperties)
	{
		//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/Filter.hx"
		{
			//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/Filter.hx"
			boolean __temp_executeDef1 = true;
			//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/Filter.hx"
			if (( field != null )) 
			{
				//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/Filter.hx"
				switch (field.hashCode())
				{
					case 121:
					{
						//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/Filter.hx"
						if (field.equals("y")) 
						{
							//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/Filter.hx"
							__temp_executeDef1 = false;
							//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/Filter.hx"
							return this.y;
						}
						
						//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/Filter.hx"
						break;
					}
					
					
					case 120:
					{
						//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/Filter.hx"
						if (field.equals("x")) 
						{
							//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/Filter.hx"
							__temp_executeDef1 = false;
							//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/Filter.hx"
							return this.x;
						}
						
						//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/Filter.hx"
						break;
					}
					
					
				}
				
			}
			
			//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/Filter.hx"
			if (__temp_executeDef1) 
			{
				//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/Filter.hx"
				return super.__hx_getField(field, throwErrors, isCheck, handleProperties);
			}
			else
			{
				//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/Filter.hx"
				throw null;
			}
			
		}
		
	}
	
	
	@Override public void __hx_getFields(haxe.root.Array<java.lang.String> baseArr)
	{
		//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/Filter.hx"
		baseArr.push("y");
		//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/Filter.hx"
		baseArr.push("x");
		//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/Filter.hx"
		super.__hx_getFields(baseArr);
	}
	
	
}


