// Generated by Haxe 4.1.3
package ln;

import haxe.root.*;

@SuppressWarnings(value={"rawtypes", "unchecked"})
public class Mesh extends haxe.lang.HxObject implements ln.Shape
{
	public Mesh(haxe.lang.EmptyObject empty)
	{
	}
	
	
	public Mesh(ln.Box _Box, haxe.root.Array<ln.Triangle> _Triangles, ln.Tree _Tree)
	{
		//line 11 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
		ln.Mesh.__hx_ctor_ln_Mesh(this, _Box, _Triangles, _Tree);
	}
	
	
	protected static void __hx_ctor_ln_Mesh(ln.Mesh __hx_this, ln.Box _Box, haxe.root.Array<ln.Triangle> _Triangles, ln.Tree _Tree)
	{
		//line 10 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
		__hx_this.Tree = null;
		//line 9 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
		__hx_this.Triangles = new haxe.root.Array<ln.Triangle>(new ln.Triangle[]{});
		//line 8 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
		__hx_this.Box = null;
		//line 11 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
		{
			//line 12 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
			__hx_this.Box = _Box;
			//line 13 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
			__hx_this.Triangles = _Triangles;
			//line 14 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
			__hx_this.Tree = _Tree;
		}
		
	}
	
	
	public ln.Box Box;
	
	public haxe.root.Array<ln.Triangle> Triangles;
	
	public ln.Tree Tree;
	
	public ln.Mesh _clone()
	{
		//line 17 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
		return new ln.Mesh(this.Box, this.Triangles, this.Tree);
	}
	
	
	public void Compile()
	{
		//line 20 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
		ln.Mesh m = this._clone();
		//line 21 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
		if (( m.Tree == null )) 
		{
			//line 22 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
			haxe.root.Array<ln.Triangle> shapes = new haxe.root.Array<ln.Triangle>(new ln.Triangle[]{});
			//line 23 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
			haxe.root.Array<ln.Triangle> _juyfg = m.Triangles;
			//line 24 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
			{
				//line 24 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
				int _g = 0;
				//line 24 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
				int _g1 = _juyfg.length;
				//line 24 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
				while (( _g < _g1 ))
				{
					//line 24 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
					int i = _g++;
					//line 25 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
					ln.Triangle triangle = _juyfg.__get(i);
					//line 26 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
					shapes.__set(i, triangle);
				}
				
			}
			
			//line 28 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
			m.Tree = ln.Ln.NewTree(((haxe.root.Array<ln.Shape>) (((haxe.root.Array) (shapes) )) ));
		}
		
	}
	
	
	public ln.Box BoundingBox()
	{
		//line 32 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
		ln.Mesh m = this._clone();
		//line 33 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
		return m.Box;
	}
	
	
	public boolean Contains(ln.Vector v, double f)
	{
		//line 36 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
		ln.Mesh m = this._clone();
		//line 37 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
		return false;
	}
	
	
	public ln.Hit Intersect(ln.Ray r)
	{
		//line 40 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
		ln.Mesh m = this._clone();
		//line 41 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
		return m.Tree.Intersect(r);
	}
	
	
	public haxe.root.Array<haxe.root.Array<ln.Vector>> Paths()
	{
		//line 44 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
		ln.Mesh m = this._clone();
		//line 45 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
		haxe.root.Array<haxe.root.Array<ln.Vector>> result = null;
		//line 46 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
		haxe.root.Array<ln.Triangle> _ntazc = m.Triangles;
		//line 47 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
		{
			//line 47 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
			int _g = 0;
			//line 47 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
			int _g1 = _ntazc.length;
			//line 47 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
			while (( _g < _g1 ))
			{
				//line 47 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
				int _1 = _g++;
				//line 48 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
				ln.Triangle t = _ntazc.__get(_1);
				//line 49 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
				result = ln._Paths.Paths_Impl_.concat(result, t.Paths());
			}
			
		}
		
		//line 51 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
		return result;
	}
	
	
	public void UpdateBoundingBox()
	{
		//line 54 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
		ln.Mesh m = this._clone();
		//line 55 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
		m.Box = ln.Ln.BoxForTriangles(m.Triangles);
	}
	
	
	public void UnitCube()
	{
		//line 58 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
		ln.Mesh m = this._clone();
		//line 59 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
		m.FitInside(new ln.Box(new ln.Vector(null, null, null), new ln.Vector(1, 1, 1)), new ln.Vector(null, null, null));
		//line 60 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
		m.MoveTo(new ln.Vector(null, null, null), new ln.Vector(0.5, 0.5, 0.5));
	}
	
	
	public void MoveTo(ln.Vector position, ln.Vector anchor)
	{
		//line 63 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
		ln.Mesh m = this._clone();
		//line 64 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
		ln.Matrix matrix = ln.Ln.Translate(position.Sub(m.Box.Anchor(anchor)));
		//line 65 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
		m.Transform(matrix);
	}
	
	
	public void FitInside(ln.Box box, ln.Vector anchor)
	{
		//line 68 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
		ln.Mesh m = this._clone();
		//line 69 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
		double scale = box.Size().Div(m.BoundingBox().Size()).MinComponent();
		//line 70 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
		ln.Vector extra = box.Size().Sub(m.BoundingBox().Size().MulScalar(scale));
		//line 71 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
		ln.Matrix matrix = ln.Ln.Identity();
		//line 72 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
		matrix = matrix.Translate(m.BoundingBox().Min.MulScalar(((double) (-1) )));
		//line 73 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
		matrix = matrix.Scale(new ln.Vector(scale, scale, scale));
		//line 74 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
		matrix = matrix.Translate(box.Min.Add(extra.Mul(anchor)));
		//line 75 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
		m.Transform(matrix);
	}
	
	
	public void Transform(ln.Matrix matrix)
	{
		//line 78 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
		ln.Mesh m = this._clone();
		//line 79 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
		haxe.root.Array<ln.Triangle> _ukkos = m.Triangles;
		//line 80 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
		{
			//line 80 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
			int _g = 0;
			//line 80 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
			int _g1 = _ukkos.length;
			//line 80 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
			while (( _g < _g1 ))
			{
				//line 80 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
				int _1 = _g++;
				//line 81 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
				ln.Triangle t = _ukkos.__get(_1);
				//line 82 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
				t.V1 = matrix.MulPosition(t.V1);
				//line 83 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
				t.V2 = matrix.MulPosition(t.V2);
				//line 84 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
				t.V3 = matrix.MulPosition(t.V3);
				//line 85 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
				t.UpdateBoundingBox();
			}
			
		}
		
		//line 87 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
		m.UpdateBoundingBox();
		//line 88 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
		m.Tree = null;
	}
	
	
	public haxe.root.Array<ln.Cube> Voxelize(double size)
	{
		//line 92 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
		ln.Mesh m = this._clone();
		//line 93 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
		double z1 = m.Box.Min.Z;
		//line 94 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
		double z2 = m.Box.Max.Z;
		//line 95 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
		haxe.ds.ObjectMap<ln.Vector, java.lang.Object> set = new haxe.ds.ObjectMap<ln.Vector, java.lang.Object>();
		//line 96 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
		double z = z1;
		//line 97 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
		while (( z <= z2 ))
		{
			//line 98 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
			ln.Plane plane = new ln.Plane(new ln.Vector(0, 0, z), new ln.Vector(0, 0, 1));
			//line 99 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
			haxe.root.Array<haxe.root.Array<ln.Vector>> paths = plane.IntersectMesh(m);
			//line 100 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
			haxe.root.Array<haxe.root.Array<ln.Vector>> _gbzya = paths;
			//line 101 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
			{
				//line 101 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
				int _g = 0;
				//line 101 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
				int _g1 = ln._Paths.Paths_Impl_._raw(_gbzya).length;
				//line 101 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
				while (( _g < _g1 ))
				{
					//line 101 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
					int _1 = _g++;
					//line 102 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
					haxe.root.Array<ln.Vector> path = ln._Paths.Paths_Impl_._raw(_gbzya).__get(_1);
					//line 103 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
					haxe.root.Array<ln.Vector> _uxiel = path;
					//line 104 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
					{
						//line 104 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
						int _g2 = 0;
						//line 104 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
						int _g3 = ln._Path.Path_Impl_._raw(_uxiel).length;
						//line 104 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
						while (( _g2 < _g3 ))
						{
							//line 104 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
							int _11 = _g2++;
							//line 105 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
							ln.Vector v = ln._Path.Path_Impl_._raw(_uxiel).__get(_11);
							//line 106 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
							double x = ( ((int) (java.lang.Math.floor(( ( v.X / size ) + 0.5 ))) ) * size );
							//line 107 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
							double y = ( ((int) (java.lang.Math.floor(( ( v.Y / size ) + 0.5 ))) ) * size );
							//line 108 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
							double z3 = ( ((int) (java.lang.Math.floor(( ( v.Z / size ) + 0.5 ))) ) * size );
							//line 109 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
							set.set(new ln.Vector(x, y, z3), true);
						}
						
					}
					
				}
				
			}
			
			//line 112 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
			z += size;
		}
		
		//line 114 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
		haxe.root.Array<ln.Cube> result = new haxe.root.Array<ln.Cube>(new ln.Cube[]{});
		//line 116 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
		{
			//line 116 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
			java.lang.Object _g4 = ((java.lang.Object) (new haxe.iterators.MapKeyValueIterator<ln.Vector, java.lang.Object>(((haxe.IMap<ln.Vector, java.lang.Object>) (((haxe.IMap) (set) )) ))) );
			//line 116 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
			while (haxe.lang.Runtime.toBool(((java.lang.Boolean) (haxe.lang.Runtime.callField(_g4, "hasNext", null)) )))
			{
				//line 116 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
				java.lang.Object _g5 = ((java.lang.Object) (haxe.lang.Runtime.callField(_g4, "next", null)) );
				//line 116 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
				ln.Vector v1 = ((ln.Vector) (haxe.lang.Runtime.getField(_g5, "key", true)) );
				//line 116 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
				boolean b = haxe.lang.Runtime.toBool(((java.lang.Boolean) (haxe.lang.Runtime.getField(_g5, "value", true)) ));
				//line 116 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
				{
					//line 117 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
					ln.Cube cube = ln.Ln.NewCube(v1.SubScalar(( size / 2 )), v1.AddScalar(( size / 2 )));
					//line 118 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
					result = result.concat(new haxe.root.Array<ln.Cube>(new ln.Cube[]{cube}));
				}
				
			}
			
		}
		
		//line 120 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
		return result;
	}
	
	
	@Override public java.lang.Object __hx_setField(java.lang.String field, java.lang.Object value, boolean handleProperties)
	{
		//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
		{
			//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
			boolean __temp_executeDef1 = true;
			//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
			if (( field != null )) 
			{
				//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
				switch (field.hashCode())
				{
					case 2615230:
					{
						//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
						if (field.equals("Tree")) 
						{
							//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
							__temp_executeDef1 = false;
							//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
							this.Tree = ((ln.Tree) (value) );
							//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
							return value;
						}
						
						//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
						break;
					}
					
					
					case 66987:
					{
						//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
						if (field.equals("Box")) 
						{
							//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
							__temp_executeDef1 = false;
							//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
							this.Box = ((ln.Box) (value) );
							//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
							return value;
						}
						
						//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
						break;
					}
					
					
					case 1189959499:
					{
						//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
						if (field.equals("Triangles")) 
						{
							//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
							__temp_executeDef1 = false;
							//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
							this.Triangles = ((haxe.root.Array<ln.Triangle>) (value) );
							//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
							return value;
						}
						
						//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
						break;
					}
					
					
				}
				
			}
			
			//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
			if (__temp_executeDef1) 
			{
				//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
				return super.__hx_setField(field, value, handleProperties);
			}
			else
			{
				//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
				throw null;
			}
			
		}
		
	}
	
	
	@Override public java.lang.Object __hx_getField(java.lang.String field, boolean throwErrors, boolean isCheck, boolean handleProperties)
	{
		//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
		{
			//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
			boolean __temp_executeDef1 = true;
			//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
			if (( field != null )) 
			{
				//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
				switch (field.hashCode())
				{
					case -1476377106:
					{
						//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
						if (field.equals("Voxelize")) 
						{
							//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
							__temp_executeDef1 = false;
							//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
							return ((haxe.lang.Function) (new haxe.lang.Closure(this, "Voxelize")) );
						}
						
						//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
						break;
					}
					
					
					case 66987:
					{
						//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
						if (field.equals("Box")) 
						{
							//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
							__temp_executeDef1 = false;
							//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
							return this.Box;
						}
						
						//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
						break;
					}
					
					
					case -1238332596:
					{
						//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
						if (field.equals("Transform")) 
						{
							//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
							__temp_executeDef1 = false;
							//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
							return ((haxe.lang.Function) (new haxe.lang.Closure(this, "Transform")) );
						}
						
						//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
						break;
					}
					
					
					case 1189959499:
					{
						//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
						if (field.equals("Triangles")) 
						{
							//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
							__temp_executeDef1 = false;
							//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
							return this.Triangles;
						}
						
						//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
						break;
					}
					
					
					case -1590012083:
					{
						//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
						if (field.equals("FitInside")) 
						{
							//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
							__temp_executeDef1 = false;
							//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
							return ((haxe.lang.Function) (new haxe.lang.Closure(this, "FitInside")) );
						}
						
						//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
						break;
					}
					
					
					case 2615230:
					{
						//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
						if (field.equals("Tree")) 
						{
							//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
							__temp_executeDef1 = false;
							//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
							return this.Tree;
						}
						
						//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
						break;
					}
					
					
					case -1984396724:
					{
						//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
						if (field.equals("MoveTo")) 
						{
							//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
							__temp_executeDef1 = false;
							//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
							return ((haxe.lang.Function) (new haxe.lang.Closure(this, "MoveTo")) );
						}
						
						//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
						break;
					}
					
					
					case -1480441762:
					{
						//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
						if (field.equals("_clone")) 
						{
							//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
							__temp_executeDef1 = false;
							//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
							return ((haxe.lang.Function) (new haxe.lang.Closure(this, "_clone")) );
						}
						
						//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
						break;
					}
					
					
					case -228518919:
					{
						//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
						if (field.equals("UnitCube")) 
						{
							//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
							__temp_executeDef1 = false;
							//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
							return ((haxe.lang.Function) (new haxe.lang.Closure(this, "UnitCube")) );
						}
						
						//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
						break;
					}
					
					
					case -1679822317:
					{
						//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
						if (field.equals("Compile")) 
						{
							//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
							__temp_executeDef1 = false;
							//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
							return ((haxe.lang.Function) (new haxe.lang.Closure(this, "Compile")) );
						}
						
						//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
						break;
					}
					
					
					case 1536947422:
					{
						//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
						if (field.equals("UpdateBoundingBox")) 
						{
							//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
							__temp_executeDef1 = false;
							//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
							return ((haxe.lang.Function) (new haxe.lang.Closure(this, "UpdateBoundingBox")) );
						}
						
						//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
						break;
					}
					
					
					case 405804391:
					{
						//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
						if (field.equals("BoundingBox")) 
						{
							//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
							__temp_executeDef1 = false;
							//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
							return ((haxe.lang.Function) (new haxe.lang.Closure(this, "BoundingBox")) );
						}
						
						//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
						break;
					}
					
					
					case 76886222:
					{
						//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
						if (field.equals("Paths")) 
						{
							//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
							__temp_executeDef1 = false;
							//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
							return ((haxe.lang.Function) (new haxe.lang.Closure(this, "Paths")) );
						}
						
						//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
						break;
					}
					
					
					case -502801857:
					{
						//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
						if (field.equals("Contains")) 
						{
							//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
							__temp_executeDef1 = false;
							//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
							return ((haxe.lang.Function) (new haxe.lang.Closure(this, "Contains")) );
						}
						
						//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
						break;
					}
					
					
					case -1787984641:
					{
						//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
						if (field.equals("Intersect")) 
						{
							//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
							__temp_executeDef1 = false;
							//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
							return ((haxe.lang.Function) (new haxe.lang.Closure(this, "Intersect")) );
						}
						
						//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
						break;
					}
					
					
				}
				
			}
			
			//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
			if (__temp_executeDef1) 
			{
				//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
				return super.__hx_getField(field, throwErrors, isCheck, handleProperties);
			}
			else
			{
				//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
				throw null;
			}
			
		}
		
	}
	
	
	@Override public java.lang.Object __hx_invokeField(java.lang.String field, java.lang.Object[] dynargs)
	{
		//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
		{
			//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
			boolean __temp_executeDef1 = true;
			//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
			if (( field != null )) 
			{
				//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
				switch (field.hashCode())
				{
					case -1476377106:
					{
						//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
						if (field.equals("Voxelize")) 
						{
							//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
							__temp_executeDef1 = false;
							//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
							return this.Voxelize(((double) (haxe.lang.Runtime.toDouble(dynargs[0])) ));
						}
						
						//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
						break;
					}
					
					
					case -1480441762:
					{
						//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
						if (field.equals("_clone")) 
						{
							//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
							__temp_executeDef1 = false;
							//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
							return this._clone();
						}
						
						//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
						break;
					}
					
					
					case -1238332596:
					{
						//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
						if (field.equals("Transform")) 
						{
							//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
							__temp_executeDef1 = false;
							//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
							this.Transform(((ln.Matrix) (dynargs[0]) ));
						}
						
						//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
						break;
					}
					
					
					case -1679822317:
					{
						//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
						if (field.equals("Compile")) 
						{
							//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
							__temp_executeDef1 = false;
							//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
							this.Compile();
						}
						
						//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
						break;
					}
					
					
					case -1590012083:
					{
						//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
						if (field.equals("FitInside")) 
						{
							//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
							__temp_executeDef1 = false;
							//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
							this.FitInside(((ln.Box) (dynargs[0]) ), ((ln.Vector) (dynargs[1]) ));
						}
						
						//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
						break;
					}
					
					
					case 405804391:
					{
						//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
						if (field.equals("BoundingBox")) 
						{
							//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
							__temp_executeDef1 = false;
							//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
							return this.BoundingBox();
						}
						
						//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
						break;
					}
					
					
					case -1984396724:
					{
						//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
						if (field.equals("MoveTo")) 
						{
							//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
							__temp_executeDef1 = false;
							//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
							this.MoveTo(((ln.Vector) (dynargs[0]) ), ((ln.Vector) (dynargs[1]) ));
						}
						
						//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
						break;
					}
					
					
					case -502801857:
					{
						//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
						if (field.equals("Contains")) 
						{
							//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
							__temp_executeDef1 = false;
							//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
							return this.Contains(((ln.Vector) (dynargs[0]) ), ((double) (haxe.lang.Runtime.toDouble(dynargs[1])) ));
						}
						
						//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
						break;
					}
					
					
					case -228518919:
					{
						//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
						if (field.equals("UnitCube")) 
						{
							//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
							__temp_executeDef1 = false;
							//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
							this.UnitCube();
						}
						
						//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
						break;
					}
					
					
					case -1787984641:
					{
						//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
						if (field.equals("Intersect")) 
						{
							//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
							__temp_executeDef1 = false;
							//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
							return this.Intersect(((ln.Ray) (dynargs[0]) ));
						}
						
						//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
						break;
					}
					
					
					case 1536947422:
					{
						//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
						if (field.equals("UpdateBoundingBox")) 
						{
							//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
							__temp_executeDef1 = false;
							//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
							this.UpdateBoundingBox();
						}
						
						//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
						break;
					}
					
					
					case 76886222:
					{
						//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
						if (field.equals("Paths")) 
						{
							//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
							__temp_executeDef1 = false;
							//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
							return this.Paths();
						}
						
						//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
						break;
					}
					
					
				}
				
			}
			
			//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
			if (__temp_executeDef1) 
			{
				//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
				return super.__hx_invokeField(field, dynargs);
			}
			
		}
		
		//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
		return null;
	}
	
	
	@Override public void __hx_getFields(haxe.root.Array<java.lang.String> baseArr)
	{
		//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
		baseArr.push("Tree");
		//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
		baseArr.push("Triangles");
		//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
		baseArr.push("Box");
		//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/Mesh.hx"
		super.__hx_getFields(baseArr);
	}
	
	
}


