// Generated by Haxe 4.1.3
package ln;

import haxe.root.*;

@SuppressWarnings(value={"rawtypes", "unchecked"})
public class Ray extends haxe.lang.HxObject
{
	public Ray(haxe.lang.EmptyObject empty)
	{
	}
	
	
	public Ray(ln.Vector _Origin, ln.Vector _Direction)
	{
		//line 9 "/Users/lingdonghuang/proj/LN.pde/ln/Ray.hx"
		ln.Ray.__hx_ctor_ln_Ray(this, _Origin, _Direction);
	}
	
	
	protected static void __hx_ctor_ln_Ray(ln.Ray __hx_this, ln.Vector _Origin, ln.Vector _Direction)
	{
		//line 8 "/Users/lingdonghuang/proj/LN.pde/ln/Ray.hx"
		__hx_this.Direction = null;
		//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/Ray.hx"
		__hx_this.Origin = null;
		//line 9 "/Users/lingdonghuang/proj/LN.pde/ln/Ray.hx"
		{
			//line 10 "/Users/lingdonghuang/proj/LN.pde/ln/Ray.hx"
			__hx_this.Origin = _Origin;
			//line 11 "/Users/lingdonghuang/proj/LN.pde/ln/Ray.hx"
			__hx_this.Direction = _Direction;
		}
		
	}
	
	
	public ln.Vector Origin;
	
	public ln.Vector Direction;
	
	public ln.Ray _clone()
	{
		//line 14 "/Users/lingdonghuang/proj/LN.pde/ln/Ray.hx"
		return new ln.Ray(this.Origin, this.Direction);
	}
	
	
	public ln.Vector Position(double t)
	{
		//line 17 "/Users/lingdonghuang/proj/LN.pde/ln/Ray.hx"
		ln.Ray r = this._clone();
		//line 18 "/Users/lingdonghuang/proj/LN.pde/ln/Ray.hx"
		return r.Origin.Add(r.Direction.MulScalar(t));
	}
	
	
	@Override public java.lang.Object __hx_setField(java.lang.String field, java.lang.Object value, boolean handleProperties)
	{
		//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/Ray.hx"
		{
			//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/Ray.hx"
			boolean __temp_executeDef1 = true;
			//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/Ray.hx"
			if (( field != null )) 
			{
				//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/Ray.hx"
				switch (field.hashCode())
				{
					case 1041377119:
					{
						//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/Ray.hx"
						if (field.equals("Direction")) 
						{
							//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/Ray.hx"
							__temp_executeDef1 = false;
							//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/Ray.hx"
							this.Direction = ((ln.Vector) (value) );
							//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/Ray.hx"
							return value;
						}
						
						//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/Ray.hx"
						break;
					}
					
					
					case -1924752570:
					{
						//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/Ray.hx"
						if (field.equals("Origin")) 
						{
							//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/Ray.hx"
							__temp_executeDef1 = false;
							//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/Ray.hx"
							this.Origin = ((ln.Vector) (value) );
							//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/Ray.hx"
							return value;
						}
						
						//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/Ray.hx"
						break;
					}
					
					
				}
				
			}
			
			//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/Ray.hx"
			if (__temp_executeDef1) 
			{
				//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/Ray.hx"
				return super.__hx_setField(field, value, handleProperties);
			}
			else
			{
				//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/Ray.hx"
				throw null;
			}
			
		}
		
	}
	
	
	@Override public java.lang.Object __hx_getField(java.lang.String field, boolean throwErrors, boolean isCheck, boolean handleProperties)
	{
		//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/Ray.hx"
		{
			//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/Ray.hx"
			boolean __temp_executeDef1 = true;
			//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/Ray.hx"
			if (( field != null )) 
			{
				//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/Ray.hx"
				switch (field.hashCode())
				{
					case 812449097:
					{
						//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/Ray.hx"
						if (field.equals("Position")) 
						{
							//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/Ray.hx"
							__temp_executeDef1 = false;
							//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/Ray.hx"
							return ((haxe.lang.Function) (new haxe.lang.Closure(this, "Position")) );
						}
						
						//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/Ray.hx"
						break;
					}
					
					
					case -1924752570:
					{
						//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/Ray.hx"
						if (field.equals("Origin")) 
						{
							//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/Ray.hx"
							__temp_executeDef1 = false;
							//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/Ray.hx"
							return this.Origin;
						}
						
						//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/Ray.hx"
						break;
					}
					
					
					case -1480441762:
					{
						//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/Ray.hx"
						if (field.equals("_clone")) 
						{
							//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/Ray.hx"
							__temp_executeDef1 = false;
							//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/Ray.hx"
							return ((haxe.lang.Function) (new haxe.lang.Closure(this, "_clone")) );
						}
						
						//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/Ray.hx"
						break;
					}
					
					
					case 1041377119:
					{
						//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/Ray.hx"
						if (field.equals("Direction")) 
						{
							//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/Ray.hx"
							__temp_executeDef1 = false;
							//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/Ray.hx"
							return this.Direction;
						}
						
						//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/Ray.hx"
						break;
					}
					
					
				}
				
			}
			
			//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/Ray.hx"
			if (__temp_executeDef1) 
			{
				//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/Ray.hx"
				return super.__hx_getField(field, throwErrors, isCheck, handleProperties);
			}
			else
			{
				//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/Ray.hx"
				throw null;
			}
			
		}
		
	}
	
	
	@Override public java.lang.Object __hx_invokeField(java.lang.String field, java.lang.Object[] dynargs)
	{
		//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/Ray.hx"
		{
			//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/Ray.hx"
			boolean __temp_executeDef1 = true;
			//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/Ray.hx"
			if (( field != null )) 
			{
				//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/Ray.hx"
				switch (field.hashCode())
				{
					case 812449097:
					{
						//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/Ray.hx"
						if (field.equals("Position")) 
						{
							//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/Ray.hx"
							__temp_executeDef1 = false;
							//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/Ray.hx"
							return this.Position(((double) (haxe.lang.Runtime.toDouble(dynargs[0])) ));
						}
						
						//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/Ray.hx"
						break;
					}
					
					
					case -1480441762:
					{
						//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/Ray.hx"
						if (field.equals("_clone")) 
						{
							//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/Ray.hx"
							__temp_executeDef1 = false;
							//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/Ray.hx"
							return this._clone();
						}
						
						//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/Ray.hx"
						break;
					}
					
					
				}
				
			}
			
			//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/Ray.hx"
			if (__temp_executeDef1) 
			{
				//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/Ray.hx"
				return super.__hx_invokeField(field, dynargs);
			}
			else
			{
				//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/Ray.hx"
				throw null;
			}
			
		}
		
	}
	
	
	@Override public void __hx_getFields(haxe.root.Array<java.lang.String> baseArr)
	{
		//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/Ray.hx"
		baseArr.push("Direction");
		//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/Ray.hx"
		baseArr.push("Origin");
		//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/Ray.hx"
		super.__hx_getFields(baseArr);
	}
	
	
}


