// Generated by Haxe 4.1.3
package ln;

import haxe.root.*;

@SuppressWarnings(value={"rawtypes", "unchecked"})
public class STLTriangle extends haxe.lang.HxObject
{
	public STLTriangle(haxe.lang.EmptyObject empty)
	{
	}
	
	
	public STLTriangle(haxe.root.Array<java.lang.Object> _V1, haxe.root.Array<java.lang.Object> _V2, haxe.root.Array<java.lang.Object> _V3)
	{
		//line 10 "/Users/lingdonghuang/proj/LN.pde/ln/STLTriangle.hx"
		ln.STLTriangle.__hx_ctor_ln_STLTriangle(this, _V1, _V2, _V3);
	}
	
	
	protected static void __hx_ctor_ln_STLTriangle(ln.STLTriangle __hx_this, haxe.root.Array<java.lang.Object> _V1, haxe.root.Array<java.lang.Object> _V2, haxe.root.Array<java.lang.Object> _V3)
	{
		//line 9 "/Users/lingdonghuang/proj/LN.pde/ln/STLTriangle.hx"
		__hx_this.V3 = new haxe.root.Array<java.lang.Object>(new java.lang.Object[]{});
		//line 8 "/Users/lingdonghuang/proj/LN.pde/ln/STLTriangle.hx"
		__hx_this.V2 = new haxe.root.Array<java.lang.Object>(new java.lang.Object[]{});
		//line 7 "/Users/lingdonghuang/proj/LN.pde/ln/STLTriangle.hx"
		__hx_this.V1 = new haxe.root.Array<java.lang.Object>(new java.lang.Object[]{});
		//line 10 "/Users/lingdonghuang/proj/LN.pde/ln/STLTriangle.hx"
		{
			//line 11 "/Users/lingdonghuang/proj/LN.pde/ln/STLTriangle.hx"
			__hx_this.V1 = _V1;
			//line 12 "/Users/lingdonghuang/proj/LN.pde/ln/STLTriangle.hx"
			__hx_this.V2 = _V2;
			//line 13 "/Users/lingdonghuang/proj/LN.pde/ln/STLTriangle.hx"
			__hx_this.V3 = _V3;
		}
		
	}
	
	
	public haxe.root.Array<java.lang.Object> V1;
	
	public haxe.root.Array<java.lang.Object> V2;
	
	public haxe.root.Array<java.lang.Object> V3;
	
	public ln.STLTriangle _clone()
	{
		//line 16 "/Users/lingdonghuang/proj/LN.pde/ln/STLTriangle.hx"
		return new ln.STLTriangle(this.V1, this.V2, this.V3);
	}
	
	
	@Override public java.lang.Object __hx_setField(java.lang.String field, java.lang.Object value, boolean handleProperties)
	{
		//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/STLTriangle.hx"
		{
			//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/STLTriangle.hx"
			boolean __temp_executeDef1 = true;
			//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/STLTriangle.hx"
			if (( field != null )) 
			{
				//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/STLTriangle.hx"
				switch (field.hashCode())
				{
					case 2717:
					{
						//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/STLTriangle.hx"
						if (field.equals("V3")) 
						{
							//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/STLTriangle.hx"
							__temp_executeDef1 = false;
							//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/STLTriangle.hx"
							this.V3 = ((haxe.root.Array<java.lang.Object>) (value) );
							//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/STLTriangle.hx"
							return value;
						}
						
						//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/STLTriangle.hx"
						break;
					}
					
					
					case 2715:
					{
						//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/STLTriangle.hx"
						if (field.equals("V1")) 
						{
							//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/STLTriangle.hx"
							__temp_executeDef1 = false;
							//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/STLTriangle.hx"
							this.V1 = ((haxe.root.Array<java.lang.Object>) (value) );
							//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/STLTriangle.hx"
							return value;
						}
						
						//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/STLTriangle.hx"
						break;
					}
					
					
					case 2716:
					{
						//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/STLTriangle.hx"
						if (field.equals("V2")) 
						{
							//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/STLTriangle.hx"
							__temp_executeDef1 = false;
							//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/STLTriangle.hx"
							this.V2 = ((haxe.root.Array<java.lang.Object>) (value) );
							//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/STLTriangle.hx"
							return value;
						}
						
						//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/STLTriangle.hx"
						break;
					}
					
					
				}
				
			}
			
			//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/STLTriangle.hx"
			if (__temp_executeDef1) 
			{
				//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/STLTriangle.hx"
				return super.__hx_setField(field, value, handleProperties);
			}
			else
			{
				//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/STLTriangle.hx"
				throw null;
			}
			
		}
		
	}
	
	
	@Override public java.lang.Object __hx_getField(java.lang.String field, boolean throwErrors, boolean isCheck, boolean handleProperties)
	{
		//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/STLTriangle.hx"
		{
			//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/STLTriangle.hx"
			boolean __temp_executeDef1 = true;
			//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/STLTriangle.hx"
			if (( field != null )) 
			{
				//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/STLTriangle.hx"
				switch (field.hashCode())
				{
					case -1480441762:
					{
						//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/STLTriangle.hx"
						if (field.equals("_clone")) 
						{
							//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/STLTriangle.hx"
							__temp_executeDef1 = false;
							//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/STLTriangle.hx"
							return ((haxe.lang.Function) (new haxe.lang.Closure(this, "_clone")) );
						}
						
						//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/STLTriangle.hx"
						break;
					}
					
					
					case 2715:
					{
						//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/STLTriangle.hx"
						if (field.equals("V1")) 
						{
							//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/STLTriangle.hx"
							__temp_executeDef1 = false;
							//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/STLTriangle.hx"
							return this.V1;
						}
						
						//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/STLTriangle.hx"
						break;
					}
					
					
					case 2717:
					{
						//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/STLTriangle.hx"
						if (field.equals("V3")) 
						{
							//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/STLTriangle.hx"
							__temp_executeDef1 = false;
							//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/STLTriangle.hx"
							return this.V3;
						}
						
						//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/STLTriangle.hx"
						break;
					}
					
					
					case 2716:
					{
						//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/STLTriangle.hx"
						if (field.equals("V2")) 
						{
							//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/STLTriangle.hx"
							__temp_executeDef1 = false;
							//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/STLTriangle.hx"
							return this.V2;
						}
						
						//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/STLTriangle.hx"
						break;
					}
					
					
				}
				
			}
			
			//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/STLTriangle.hx"
			if (__temp_executeDef1) 
			{
				//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/STLTriangle.hx"
				return super.__hx_getField(field, throwErrors, isCheck, handleProperties);
			}
			else
			{
				//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/STLTriangle.hx"
				throw null;
			}
			
		}
		
	}
	
	
	@Override public java.lang.Object __hx_invokeField(java.lang.String field, java.lang.Object[] dynargs)
	{
		//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/STLTriangle.hx"
		{
			//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/STLTriangle.hx"
			boolean __temp_executeDef1 = true;
			//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/STLTriangle.hx"
			if (( field != null )) 
			{
				//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/STLTriangle.hx"
				switch (field.hashCode())
				{
					case -1480441762:
					{
						//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/STLTriangle.hx"
						if (field.equals("_clone")) 
						{
							//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/STLTriangle.hx"
							__temp_executeDef1 = false;
							//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/STLTriangle.hx"
							return this._clone();
						}
						
						//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/STLTriangle.hx"
						break;
					}
					
					
				}
				
			}
			
			//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/STLTriangle.hx"
			if (__temp_executeDef1) 
			{
				//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/STLTriangle.hx"
				return super.__hx_invokeField(field, dynargs);
			}
			else
			{
				//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/STLTriangle.hx"
				throw null;
			}
			
		}
		
	}
	
	
	@Override public void __hx_getFields(haxe.root.Array<java.lang.String> baseArr)
	{
		//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/STLTriangle.hx"
		baseArr.push("V3");
		//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/STLTriangle.hx"
		baseArr.push("V2");
		//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/STLTriangle.hx"
		baseArr.push("V1");
		//line 6 "/Users/lingdonghuang/proj/LN.pde/ln/STLTriangle.hx"
		super.__hx_getFields(baseArr);
	}
	
	
}


