// Generated by Haxe 4.1.3
package ln._Paths;

import haxe.root.*;

@SuppressWarnings(value={"rawtypes", "unchecked"})
public final class Paths_Impl_
{
	public static haxe.root.Array<haxe.root.Array<ln.Vector>> _new(haxe.root.Array<haxe.root.Array<ln.Vector>> data)
	{
		//line 8 "/Users/lingdonghuang/proj/LN.pde/ln/Paths.hx"
		haxe.root.Array<haxe.root.Array<ln.Vector>> this1 = data;
		//line 8 "/Users/lingdonghuang/proj/LN.pde/ln/Paths.hx"
		return ((haxe.root.Array<haxe.root.Array<ln.Vector>>) (this1) );
	}
	
	
	public static ln.Box BoundingBox(haxe.root.Array<haxe.root.Array<ln.Vector>> this1)
	{
		//line 12 "/Users/lingdonghuang/proj/LN.pde/ln/Paths.hx"
		haxe.root.Array<haxe.root.Array<ln.Vector>> p = this1;
		//line 13 "/Users/lingdonghuang/proj/LN.pde/ln/Paths.hx"
		ln.Box box = ln._Path.Path_Impl_.BoundingBox(p.__get(0));
		//line 14 "/Users/lingdonghuang/proj/LN.pde/ln/Paths.hx"
		haxe.root.Array<haxe.root.Array<ln.Vector>> _cvvol = p;
		//line 15 "/Users/lingdonghuang/proj/LN.pde/ln/Paths.hx"
		{
			//line 15 "/Users/lingdonghuang/proj/LN.pde/ln/Paths.hx"
			int _g = 0;
			//line 15 "/Users/lingdonghuang/proj/LN.pde/ln/Paths.hx"
			int _g1 = _cvvol.length;
			//line 15 "/Users/lingdonghuang/proj/LN.pde/ln/Paths.hx"
			while (( _g < _g1 ))
			{
				//line 15 "/Users/lingdonghuang/proj/LN.pde/ln/Paths.hx"
				int _1 = _g++;
				//line 16 "/Users/lingdonghuang/proj/LN.pde/ln/Paths.hx"
				haxe.root.Array<ln.Vector> path = _cvvol.__get(_1);
				//line 17 "/Users/lingdonghuang/proj/LN.pde/ln/Paths.hx"
				box = box.Extend(ln._Path.Path_Impl_.BoundingBox(path));
			}
			
		}
		
		//line 19 "/Users/lingdonghuang/proj/LN.pde/ln/Paths.hx"
		return box;
	}
	
	
	public static haxe.root.Array<haxe.root.Array<ln.Vector>> _raw(haxe.root.Array<haxe.root.Array<ln.Vector>> this1)
	{
		//line 22 "/Users/lingdonghuang/proj/LN.pde/ln/Paths.hx"
		return this1;
	}
	
	
	public static haxe.root.Array<haxe.root.Array<ln.Vector>> concat(haxe.root.Array<haxe.root.Array<ln.Vector>> this1, haxe.root.Array<haxe.root.Array<ln.Vector>> other)
	{
		//line 25 "/Users/lingdonghuang/proj/LN.pde/ln/Paths.hx"
		return ln._Paths.Paths_Impl_._new(this1.concat(ln._Paths.Paths_Impl_._raw(other)));
	}
	
	
	public static haxe.root.Array<haxe.root.Array<ln.Vector>> Transform(haxe.root.Array<haxe.root.Array<ln.Vector>> this1, ln.Matrix matrix)
	{
		//line 28 "/Users/lingdonghuang/proj/LN.pde/ln/Paths.hx"
		haxe.root.Array<haxe.root.Array<ln.Vector>> p = this1;
		//line 29 "/Users/lingdonghuang/proj/LN.pde/ln/Paths.hx"
		haxe.root.Array<haxe.root.Array<ln.Vector>> result = ln._Paths.Paths_Impl_._new(new haxe.root.Array<haxe.root.Array<ln.Vector>>(new haxe.root.Array[]{}));
		//line 30 "/Users/lingdonghuang/proj/LN.pde/ln/Paths.hx"
		haxe.root.Array<haxe.root.Array<ln.Vector>> _xdcfw = p;
		//line 31 "/Users/lingdonghuang/proj/LN.pde/ln/Paths.hx"
		{
			//line 31 "/Users/lingdonghuang/proj/LN.pde/ln/Paths.hx"
			int _g = 0;
			//line 31 "/Users/lingdonghuang/proj/LN.pde/ln/Paths.hx"
			int _g1 = _xdcfw.length;
			//line 31 "/Users/lingdonghuang/proj/LN.pde/ln/Paths.hx"
			while (( _g < _g1 ))
			{
				//line 31 "/Users/lingdonghuang/proj/LN.pde/ln/Paths.hx"
				int _1 = _g++;
				//line 32 "/Users/lingdonghuang/proj/LN.pde/ln/Paths.hx"
				haxe.root.Array<ln.Vector> path = _xdcfw.__get(_1);
				//line 33 "/Users/lingdonghuang/proj/LN.pde/ln/Paths.hx"
				result = ln._Paths.Paths_Impl_.concat(result, ln._Paths.Paths_Impl_._new(new haxe.root.Array<haxe.root.Array<ln.Vector>>(new haxe.root.Array[]{ln._Path.Path_Impl_.Transform(path, matrix)})));
			}
			
		}
		
		//line 35 "/Users/lingdonghuang/proj/LN.pde/ln/Paths.hx"
		return result;
	}
	
	
	public static haxe.root.Array<haxe.root.Array<ln.Vector>> Chop(haxe.root.Array<haxe.root.Array<ln.Vector>> this1, double step)
	{
		//line 38 "/Users/lingdonghuang/proj/LN.pde/ln/Paths.hx"
		haxe.root.Array<haxe.root.Array<ln.Vector>> p = this1;
		//line 39 "/Users/lingdonghuang/proj/LN.pde/ln/Paths.hx"
		haxe.root.Array<haxe.root.Array<ln.Vector>> result = ln._Paths.Paths_Impl_._new(new haxe.root.Array<haxe.root.Array<ln.Vector>>(new haxe.root.Array[]{}));
		//line 40 "/Users/lingdonghuang/proj/LN.pde/ln/Paths.hx"
		haxe.root.Array<haxe.root.Array<ln.Vector>> _ncdtf = p;
		//line 41 "/Users/lingdonghuang/proj/LN.pde/ln/Paths.hx"
		{
			//line 41 "/Users/lingdonghuang/proj/LN.pde/ln/Paths.hx"
			int _g = 0;
			//line 41 "/Users/lingdonghuang/proj/LN.pde/ln/Paths.hx"
			int _g1 = _ncdtf.length;
			//line 41 "/Users/lingdonghuang/proj/LN.pde/ln/Paths.hx"
			while (( _g < _g1 ))
			{
				//line 41 "/Users/lingdonghuang/proj/LN.pde/ln/Paths.hx"
				int _1 = _g++;
				//line 42 "/Users/lingdonghuang/proj/LN.pde/ln/Paths.hx"
				haxe.root.Array<ln.Vector> path = _ncdtf.__get(_1);
				//line 43 "/Users/lingdonghuang/proj/LN.pde/ln/Paths.hx"
				result = ln._Paths.Paths_Impl_.concat(result, ln._Paths.Paths_Impl_._new(new haxe.root.Array<haxe.root.Array<ln.Vector>>(new haxe.root.Array[]{ln._Path.Path_Impl_.Chop(path, step)})));
			}
			
		}
		
		//line 45 "/Users/lingdonghuang/proj/LN.pde/ln/Paths.hx"
		return result;
	}
	
	
	public static haxe.root.Array<haxe.root.Array<ln.Vector>> Filter(haxe.root.Array<haxe.root.Array<ln.Vector>> this1, ln.Filter f)
	{
		//line 48 "/Users/lingdonghuang/proj/LN.pde/ln/Paths.hx"
		haxe.root.Array<haxe.root.Array<ln.Vector>> p = this1;
		//line 49 "/Users/lingdonghuang/proj/LN.pde/ln/Paths.hx"
		haxe.root.Array<haxe.root.Array<ln.Vector>> result = ln._Paths.Paths_Impl_._new(new haxe.root.Array<haxe.root.Array<ln.Vector>>(new haxe.root.Array[]{}));
		//line 50 "/Users/lingdonghuang/proj/LN.pde/ln/Paths.hx"
		haxe.root.Array<haxe.root.Array<ln.Vector>> _zbfhq = p;
		//line 51 "/Users/lingdonghuang/proj/LN.pde/ln/Paths.hx"
		{
			//line 51 "/Users/lingdonghuang/proj/LN.pde/ln/Paths.hx"
			int _g = 0;
			//line 51 "/Users/lingdonghuang/proj/LN.pde/ln/Paths.hx"
			int _g1 = _zbfhq.length;
			//line 51 "/Users/lingdonghuang/proj/LN.pde/ln/Paths.hx"
			while (( _g < _g1 ))
			{
				//line 51 "/Users/lingdonghuang/proj/LN.pde/ln/Paths.hx"
				int _1 = _g++;
				//line 52 "/Users/lingdonghuang/proj/LN.pde/ln/Paths.hx"
				haxe.root.Array<ln.Vector> path = _zbfhq.__get(_1);
				//line 53 "/Users/lingdonghuang/proj/LN.pde/ln/Paths.hx"
				result = ln._Paths.Paths_Impl_.concat(result, ln._Path.Path_Impl_.Filter(path, f));
			}
			
		}
		
		//line 55 "/Users/lingdonghuang/proj/LN.pde/ln/Paths.hx"
		return result;
	}
	
	
	public static haxe.root.Array<haxe.root.Array<ln.Vector>> Simplify(haxe.root.Array<haxe.root.Array<ln.Vector>> this1, double threshold)
	{
		//line 58 "/Users/lingdonghuang/proj/LN.pde/ln/Paths.hx"
		haxe.root.Array<haxe.root.Array<ln.Vector>> p = this1;
		//line 59 "/Users/lingdonghuang/proj/LN.pde/ln/Paths.hx"
		haxe.root.Array<haxe.root.Array<ln.Vector>> result = ln._Paths.Paths_Impl_._new(new haxe.root.Array<haxe.root.Array<ln.Vector>>(new haxe.root.Array[]{}));
		//line 60 "/Users/lingdonghuang/proj/LN.pde/ln/Paths.hx"
		haxe.root.Array<haxe.root.Array<ln.Vector>> _pcxdb = p;
		//line 61 "/Users/lingdonghuang/proj/LN.pde/ln/Paths.hx"
		{
			//line 61 "/Users/lingdonghuang/proj/LN.pde/ln/Paths.hx"
			int _g = 0;
			//line 61 "/Users/lingdonghuang/proj/LN.pde/ln/Paths.hx"
			int _g1 = _pcxdb.length;
			//line 61 "/Users/lingdonghuang/proj/LN.pde/ln/Paths.hx"
			while (( _g < _g1 ))
			{
				//line 61 "/Users/lingdonghuang/proj/LN.pde/ln/Paths.hx"
				int _1 = _g++;
				//line 62 "/Users/lingdonghuang/proj/LN.pde/ln/Paths.hx"
				haxe.root.Array<ln.Vector> path = _pcxdb.__get(_1);
				//line 63 "/Users/lingdonghuang/proj/LN.pde/ln/Paths.hx"
				result = ln._Paths.Paths_Impl_.concat(result, ln._Paths.Paths_Impl_._new(new haxe.root.Array<haxe.root.Array<ln.Vector>>(new haxe.root.Array[]{ln._Path.Path_Impl_.Simplify(path, threshold)})));
			}
			
		}
		
		//line 65 "/Users/lingdonghuang/proj/LN.pde/ln/Paths.hx"
		return result;
	}
	
	
	public static void Print(haxe.root.Array<haxe.root.Array<ln.Vector>> this1)
	{
		//line 68 "/Users/lingdonghuang/proj/LN.pde/ln/Paths.hx"
		haxe.root.Array<haxe.root.Array<ln.Vector>> p = this1;
		//line 69 "/Users/lingdonghuang/proj/LN.pde/ln/Paths.hx"
		haxe.root.Array<haxe.root.Array<ln.Vector>> _dgrwx = p;
		//line 70 "/Users/lingdonghuang/proj/LN.pde/ln/Paths.hx"
		{
			//line 70 "/Users/lingdonghuang/proj/LN.pde/ln/Paths.hx"
			int _g = 0;
			//line 70 "/Users/lingdonghuang/proj/LN.pde/ln/Paths.hx"
			int _g1 = _dgrwx.length;
			//line 70 "/Users/lingdonghuang/proj/LN.pde/ln/Paths.hx"
			while (( _g < _g1 ))
			{
				//line 70 "/Users/lingdonghuang/proj/LN.pde/ln/Paths.hx"
				int _1 = _g++;
				//line 71 "/Users/lingdonghuang/proj/LN.pde/ln/Paths.hx"
				haxe.root.Array<ln.Vector> path = _dgrwx.__get(_1);
				//line 72 "/Users/lingdonghuang/proj/LN.pde/ln/Paths.hx"
				ln._Path.Path_Impl_.Print(path);
			}
			
		}
		
	}
	
	
	public static java.lang.String String(haxe.root.Array<haxe.root.Array<ln.Vector>> this1)
	{
		//line 76 "/Users/lingdonghuang/proj/LN.pde/ln/Paths.hx"
		haxe.root.Array<haxe.root.Array<ln.Vector>> p = this1;
		//line 77 "/Users/lingdonghuang/proj/LN.pde/ln/Paths.hx"
		haxe.root.Array<java.lang.String> parts = new haxe.root.Array<java.lang.String>(new java.lang.String[]{});
		//line 78 "/Users/lingdonghuang/proj/LN.pde/ln/Paths.hx"
		haxe.root.Array<haxe.root.Array<ln.Vector>> _bgbej = p;
		//line 79 "/Users/lingdonghuang/proj/LN.pde/ln/Paths.hx"
		{
			//line 79 "/Users/lingdonghuang/proj/LN.pde/ln/Paths.hx"
			int _g = 0;
			//line 79 "/Users/lingdonghuang/proj/LN.pde/ln/Paths.hx"
			int _g1 = _bgbej.length;
			//line 79 "/Users/lingdonghuang/proj/LN.pde/ln/Paths.hx"
			while (( _g < _g1 ))
			{
				//line 79 "/Users/lingdonghuang/proj/LN.pde/ln/Paths.hx"
				int _1 = _g++;
				//line 80 "/Users/lingdonghuang/proj/LN.pde/ln/Paths.hx"
				haxe.root.Array<ln.Vector> path = _bgbej.__get(_1);
				//line 81 "/Users/lingdonghuang/proj/LN.pde/ln/Paths.hx"
				parts = parts.concat(new haxe.root.Array<java.lang.String>(new java.lang.String[]{ln._Path.Path_Impl_.String(path)}));
			}
			
		}
		
		//line 83 "/Users/lingdonghuang/proj/LN.pde/ln/Paths.hx"
		return parts.join("\n");
	}
	
	
	public static java.lang.String ToSVG(haxe.root.Array<haxe.root.Array<ln.Vector>> this1, double width, double height)
	{
		//line 86 "/Users/lingdonghuang/proj/LN.pde/ln/Paths.hx"
		haxe.root.Array<haxe.root.Array<ln.Vector>> p = this1;
		//line 87 "/Users/lingdonghuang/proj/LN.pde/ln/Paths.hx"
		haxe.root.Array<java.lang.String> lines = new haxe.root.Array<java.lang.String>(new java.lang.String[]{});
		//line 88 "/Users/lingdonghuang/proj/LN.pde/ln/Paths.hx"
		lines.push(( ( ( ( "<svg width=\"" + haxe.lang.Runtime.toString(width) ) + "\" height=\"" ) + haxe.lang.Runtime.toString(height) ) + "\" version=\"1.1\" baseProfile=\"full\" xmlns=\"http://www.w3.org/2000/svg\">" ));
		//line 89 "/Users/lingdonghuang/proj/LN.pde/ln/Paths.hx"
		lines.push(( ( "<g transform=\"translate(0," + haxe.lang.Runtime.toString(height) ) + ") scale(1,-1)\">" ));
		//line 90 "/Users/lingdonghuang/proj/LN.pde/ln/Paths.hx"
		haxe.root.Array<haxe.root.Array<ln.Vector>> _ztlmi = p;
		//line 91 "/Users/lingdonghuang/proj/LN.pde/ln/Paths.hx"
		{
			//line 91 "/Users/lingdonghuang/proj/LN.pde/ln/Paths.hx"
			int _g = 0;
			//line 91 "/Users/lingdonghuang/proj/LN.pde/ln/Paths.hx"
			int _g1 = _ztlmi.length;
			//line 91 "/Users/lingdonghuang/proj/LN.pde/ln/Paths.hx"
			while (( _g < _g1 ))
			{
				//line 91 "/Users/lingdonghuang/proj/LN.pde/ln/Paths.hx"
				int _1 = _g++;
				//line 92 "/Users/lingdonghuang/proj/LN.pde/ln/Paths.hx"
				haxe.root.Array<ln.Vector> path = _ztlmi.__get(_1);
				//line 93 "/Users/lingdonghuang/proj/LN.pde/ln/Paths.hx"
				lines = lines.concat(new haxe.root.Array<java.lang.String>(new java.lang.String[]{ln._Path.Path_Impl_.ToSVG(path)}));
			}
			
		}
		
		//line 95 "/Users/lingdonghuang/proj/LN.pde/ln/Paths.hx"
		lines = lines.concat(new haxe.root.Array<java.lang.String>(new java.lang.String[]{"</g></svg>"}));
		//line 96 "/Users/lingdonghuang/proj/LN.pde/ln/Paths.hx"
		return lines.join("\n");
	}
	
	
}


